#!/bin/bash
# Create symbolic links in the corresponding possitions for the three
# config files in the my_files repository. 

ln -sf $PWD/bashrc ~/.bashrc

if test -e ~/.emacs.d
then
    mv ~/.emacs.d ~/.emacs.d_bu
    rm -rf ~/.emacs.d
fi
ln -sf $PWD/emacs.d ~/.emacs.d

if test -e ~/.local/bin
then
    mv ~/.local/bin  ~/.local/bin_bu
    rm -rf ~/.local/bin
fi
ln -sf $PWD/bin ~/.local/bin
