#!/bin/bash
# Create symbolic links in the corresponding possitions for the three
# config files in the my_files repository. 

back_up () {
    if [ -L $1 ]
    then
	rm $1
    elif [ -e $1 ]
    then
	mv $1 $1_bu_$(date +"%m%d%H%M%S")
    fi
}

back_up ~/.bashrc
ln -sf $PWD/bashrc ~/.bashrc

back_up ~/.emacs.d
ln -sf $PWD/emacs.d ~/.emacs.d

back_up ~/.local/bin
ln -sf $PWD/bin ~/.local/bin
